/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import util.RenderImage;

/**
 *
 * @author JMMOLLER
 */
public class Inicio extends javax.swing.JFrame {
    private int total_p = 10;
    private int pendientes = 3;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        
        var RI = new RenderImage(this);
        RI.setImageLabel(jlFotoUsuario, "siNoTieneFoto2.jpg");
        
        RI.setIconFrame();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }
    
    private void mostrarPendientes(int total, int completado, Graphics graph) {
        lblPenText.setText("Pendiente(s): " + Integer.toString(total - completado));
        lblPenTextC.setText("Completado(s): " + completado);
        graficar(total, completado, graph);
    }
    
    public void graficar(int total, int completado, Graphics graph){

        int tareasPendientes = total - completado;

        double porcentajeCompletadas = (double) completado / total;
        double porcentajePendientes = (double) tareasPendientes / total;

        int anguloCompletadas = (int) (porcentajeCompletadas * 360);
        int anguloPendientes = (int) (porcentajePendientes * 360);

        int radio = 100;
        int centroPanel = 75; // Mitad de 150 (tamaño del JPanel)
        int centroCirculo = centroPanel - radio / 2; // Centra el círculo en el JPanel
        Color color_completado = new Color(102,255,102); // Crea el color para los completados
        Color color_pendiene = new Color(255,255,51); // Crea el color para los pendientes

        graph.setColor(color_completado);
        graph.fillArc(centroCirculo, centroCirculo, radio, radio, 0, anguloCompletadas);
        graph.setColor(color_pendiene);
        graph.fillArc(centroCirculo, centroCirculo, radio, radio, anguloCompletadas, anguloPendientes);
    }
    
    public void handleCursorChange(boolean mouseEntered){
        if(mouseEntered){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }else{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGraph = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics graph){
                super.paint(graph);

                mostrarPendientes(total_p, pendientes, graph);
            }
        };
        panelRound1 = new util.PanelRound();
        DashBoard = new util.PanelRound();
        lblLogo = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        exit = new util.PanelRound();
        jButton7 = new javax.swing.JButton();
        panelRound2 = new util.PanelRound();
        jlFotoUsuario = new javax.swing.JLabel();
        rSButtonCustom1 = new rsbuttoncustom.RSButtonCustom();
        rSButtonCustom2 = new rsbuttoncustom.RSButtonCustom();
        jButton13 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        contentRecent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitleRecent = new javax.swing.JLabel();
        contentClients = new javax.swing.JPanel();
        lblTitleClients = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        contentProducts = new javax.swing.JPanel();
        lblTitleProducts = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        contentPendings = new javax.swing.JPanel();
        lblTitlePendings = new javax.swing.JLabel();
        lblPenText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblPenTextC = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        PanelGraph.setBackground(new java.awt.Color(35, 35, 35));
        PanelGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        PanelGraph.setFocusable(false);
        PanelGraph.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelGraphLayout = new javax.swing.GroupLayout(PanelGraph);
        PanelGraph.setLayout(PanelGraphLayout);
        PanelGraphLayout.setHorizontalGroup(
            PanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        PanelGraphLayout.setVerticalGroup(
            PanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panelRound1.setBackground(new java.awt.Color(35, 35, 35));
        panelRound1.setPreferredSize(new java.awt.Dimension(1230, 530));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashBoard.setBackground(new java.awt.Color(27, 27, 27));
        DashBoard.setPreferredSize(new java.awt.Dimension(1230, 530));
        DashBoard.setRoundBottomLeft(30);
        DashBoard.setRoundTopLeft(30);
        DashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-150.png"))); // NOI18N
        lblLogo.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        DashBoard.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 150));

        jButton8.setBackground(new java.awt.Color(27, 27, 27));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/casa (1).png"))); // NOI18N
        jButton8.setText("            Home");
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        DashBoard.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 50));

        jButton9.setBackground(new java.awt.Color(27, 27, 27));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario.png"))); // NOI18N
        jButton9.setText("         Usuarios");
        jButton9.setContentAreaFilled(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        DashBoard.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        jButton10.setBackground(new java.awt.Color(27, 27, 27));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gas.png"))); // NOI18N
        jButton10.setText("       Productos");
        jButton10.setContentAreaFilled(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        DashBoard.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 50));

        jButton11.setBackground(new java.awt.Color(27, 27, 27));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedor.png"))); // NOI18N
        jButton11.setText("      Provedores");
        jButton11.setContentAreaFilled(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        DashBoard.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 50));

        exit.setBackground(new java.awt.Color(43, 209, 195));
        exit.setRoundBottomLeft(15);
        exit.setRoundBottomRight(15);
        exit.setRoundTopLeft(15);
        exit.setRoundTopRight(15);

        jButton7.setBackground(new java.awt.Color(27, 27, 27));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Exit");
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DashBoard.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 200, 50));

        panelRound2.setBackground(new java.awt.Color(56, 56, 56));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jlFotoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siNoTieneFoto2.jpg"))); // NOI18N
        jlFotoUsuario.setText("jLabel1");

        rSButtonCustom1.setBackground(new java.awt.Color(27, 27, 27));
        rSButtonCustom1.setForeground(new java.awt.Color(43, 209, 195));
        rSButtonCustom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/configuraciones.png"))); // NOI18N
        rSButtonCustom1.setColorMaterial(new java.awt.Color(43, 209, 195));
        rSButtonCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCustom1ActionPerformed(evt);
            }
        });

        rSButtonCustom2.setBackground(new java.awt.Color(27, 27, 27));
        rSButtonCustom2.setForeground(new java.awt.Color(43, 209, 195));
        rSButtonCustom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/imagen.png"))); // NOI18N
        rSButtonCustom2.setColorMaterial(new java.awt.Color(43, 209, 195));
        rSButtonCustom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCustom2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlFotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(jlFotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(rSButtonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButtonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        DashBoard.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 200, 200));

        jButton13.setBackground(new java.awt.Color(27, 27, 27));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inventario (1).png"))); // NOI18N
        jButton13.setText("        Inventario");
        jButton13.setContentAreaFilled(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        DashBoard.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 50));

        panelRound1.add(DashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("¡Bienvenido, usuario!");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        contentRecent.setBackground(new java.awt.Color(35, 35, 35));
        contentRecent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha venta", "Producto", "Cantidad", "Cliente", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        contentRecent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 640, 300));

        lblTitleRecent.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lblTitleRecent.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleRecent.setText("Ventas Recientes");
        contentRecent.add(lblTitleRecent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        panelRound1.add(contentRecent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 540, 340));

        contentClients.setBackground(new java.awt.Color(35, 35, 35));
        contentClients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleClients.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lblTitleClients.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleClients.setText("Mejores Clientes");
        contentClients.add(lblTitleClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombres", "Total compras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        contentClients.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 220));

        panelRound1.add(contentClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 310, 260));

        contentProducts.setBackground(new java.awt.Color(35, 35, 35));
        contentProducts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleProducts.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lblTitleProducts.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleProducts.setText("Productos Más Vendidos");
        contentProducts.add(lblTitleProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Stock"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        contentProducts.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 340, 220));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        contentProducts.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 10, 270));

        panelRound1.add(contentProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 440, 340, 260));

        contentPendings.setBackground(new java.awt.Color(35, 35, 35));
        contentPendings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitlePendings.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lblTitlePendings.setForeground(new java.awt.Color(255, 255, 255));
        lblTitlePendings.setText("Ventas Pendientes");
        contentPendings.add(lblTitlePendings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblPenText.setForeground(new java.awt.Color(255, 255, 255));
        lblPenText.setText("Pendiente(s): 0");
        contentPendings.add(lblPenText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 229, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPendings.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 225, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        contentPendings.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 220, 5, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        contentPendings.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 225, -1, -1));

        lblPenTextC.setForeground(new java.awt.Color(255, 255, 255));
        lblPenTextC.setText("Completado(s): 0");
        contentPendings.add(lblPenTextC, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 229, -1, -1));

        panelRound1.add(contentPendings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 240, 260));
        panelRound1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 960, 10));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarPendientes(20, 7, PanelGraph.getGraphics());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void rSButtonCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCustom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonCustom1ActionPerformed

    private void rSButtonCustom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCustom2ActionPerformed
        JFileChooser jf = new JFileChooser();
            jf.setMultiSelectionEnabled(false);

            if (jf.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                try {
                    BufferedImage originalImage = ImageIO.read(selectedFile);
                    int newWidth = 100;  
                    int newHeight = 130; 
                    Image resizedImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
  
                    BufferedImage bufferedResizedImage = new BufferedImage(newWidth, newHeight, BufferedImage.TYPE_INT_ARGB);
                    bufferedResizedImage.getGraphics().drawImage(resizedImage, 0, 0, null);
                    ImageIO.write(bufferedResizedImage, "png", new File("src/Imagenes/siNoTieneFoto2.jpg"));

                    jlFotoUsuario.setIcon(new ImageIcon(resizedImage));
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_rSButtonCustom2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.PanelRound DashBoard;
    private javax.swing.JPanel PanelGraph;
    private javax.swing.JPanel contentClients;
    private javax.swing.JPanel contentPendings;
    private javax.swing.JPanel contentProducts;
    private javax.swing.JPanel contentRecent;
    private util.PanelRound exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel jlFotoUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPenText;
    private javax.swing.JLabel lblPenTextC;
    private javax.swing.JLabel lblTitleClients;
    private javax.swing.JLabel lblTitlePendings;
    private javax.swing.JLabel lblTitleProducts;
    private javax.swing.JLabel lblTitleRecent;
    private util.PanelRound panelRound1;
    private util.PanelRound panelRound2;
    private rsbuttoncustom.RSButtonCustom rSButtonCustom1;
    private rsbuttoncustom.RSButtonCustom rSButtonCustom2;
    // End of variables declaration//GEN-END:variables
}
