/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.UserLogged;
import DAO.UsuarioDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import util.RenderImage;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public final class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));

        var RI = new RenderImage(this);
        RI.setImageLabel(jlLogin, "CamionGas.png");
        RI.setIconFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSProgressCircleAnimatedUnoBeanInfo1 = new rojerusan.componentes.RSProgressCircleAnimatedUnoBeanInfo();
        panelRound1 = new util.PanelRound();
        panelRound2 = new util.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfNombreUser = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfContraseñaUser = new javax.swing.JPasswordField();
        jCheckBox3 = new javax.swing.JCheckBox();
        panelRound3 = new util.PanelRound();
        btnIngresarLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1030, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(35, 35, 35));
        panelRound1.setPreferredSize(new java.awt.Dimension(1230, 530));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(27, 27, 27));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(43, 209, 195));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Iniciar");
        panelRound2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 56));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Sesión");
        panelRound2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 56));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Usuario:");
        panelRound2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 132, -1, -1));

        tfNombreUser.setBackground(new java.awt.Color(56, 56, 56));
        tfNombreUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNombreUser.setForeground(new java.awt.Color(204, 204, 204));
        tfNombreUser.setBorder(new EmptyBorder(10, 10, 10, 10));
        tfNombreUser.setCaretColor(new java.awt.Color(255, 255, 255));
        panelRound2.add(tfNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 162, 236, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Contraseña:");
        panelRound2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 222, -1, -1));

        tfContraseñaUser.setBackground(new java.awt.Color(56, 56, 56));
        tfContraseñaUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfContraseñaUser.setForeground(new java.awt.Color(204, 204, 204));
        tfContraseñaUser.setBorder(new EmptyBorder(10,10,10,10));
        tfContraseñaUser.setCaretColor(new java.awt.Color(255, 255, 255));
        tfContraseñaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseñaUserActionPerformed(evt);
            }
        });
        tfContraseñaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfContraseñaUserKeyPressed(evt);
            }
        });
        panelRound2.add(tfContraseñaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 252, 236, 40));

        jCheckBox3.setBackground(new java.awt.Color(27, 27, 27));
        jCheckBox3.setForeground(new java.awt.Color(153, 153, 153));
        jCheckBox3.setText("Mostrar");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        panelRound2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 304, 70, 30));

        panelRound3.setBackground(new java.awt.Color(43, 209, 195));
        panelRound3.setForeground(new java.awt.Color(255, 255, 255));
        panelRound3.setToolTipText("");
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarLogin.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresarLogin.setText("Ingresar");
        btnIngresarLogin.setContentAreaFilled(false);
        btnIngresarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIngresarLogin.setSelected(true);
        btnIngresarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarLoginMouseClicked(evt);
            }
        });
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleLoginClick(evt);
            }
        });
        panelRound3.add(btnIngresarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, -1));

        jLabel7.setForeground(new java.awt.Color(255, 180, 40));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario (1).png"))); // NOI18N
        panelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 321, 46));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 320, 410));

        jlLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CamionGas.png"))); // NOI18N
        jlLogin.setText("jLabel1");
        jlLogin.setPreferredSize(new java.awt.Dimension(589, 550));
        panelRound1.add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 570));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/celestex.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleClick(evt);
            }
        });
        panelRound1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 18, 30, -1));
        btnClose.getAccessibleContext().setAccessibleName("Cerrar ventana");

        jLabel1.setForeground(new java.awt.Color(32, 158, 147));
        jLabel1.setText("¿No tienes cuenta?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleRegisterClick(evt);
            }
        });
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("Ir a ventana de registro");

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void handleClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleClick
        System.exit(0);
    }//GEN-LAST:event_handleClick

    private void btnIngresarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarLoginMouseClicked

    private void handleRegisterClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleRegisterClick
        Registro view = new Registro();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_handleRegisterClick

    private void handleLoginClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleLoginClick
        String nombre = tfNombreUser.getText().trim();
        String contraseña = new String(tfContraseñaUser.getPassword());

        if (nombre.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        } else {
            new UsuarioDAO().authUser(nombre, contraseña);

            if (UserLogged.getIsLogged() == null) {
                JOptionPane.showMessageDialog(null, "Credenciales no válidas.");
                return;
            }
            
            dispose();
            Cargando view = new Cargando(true, UserLogged.getPRIVILEGIO());
            view.setVisible(true);
        }
    }//GEN-LAST:event_handleLoginClick

    private void tfContraseñaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseñaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseñaUserActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) {
            tfContraseñaUser.setEchoChar((char) 0);
        } else {
            tfContraseñaUser.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setIcon(new ImageIcon(getClass().getResource("/Iconos/c11.png")));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setIcon(new ImageIcon(getClass().getResource("/Iconos/celestex.png")));
    }//GEN-LAST:event_btnCloseMouseExited

    private void tfContraseñaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfContraseñaUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnIngresarLogin.doClick();
        }
    }//GEN-LAST:event_tfContraseñaUserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnIngresarLogin;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlLogin;
    private util.PanelRound panelRound1;
    private util.PanelRound panelRound2;
    private util.PanelRound panelRound3;
    private rojerusan.componentes.RSProgressCircleAnimatedUnoBeanInfo rSProgressCircleAnimatedUnoBeanInfo1;
    private javax.swing.JPasswordField tfContraseñaUser;
    private javax.swing.JTextField tfNombreUser;
    // End of variables declaration//GEN-END:variables
}
