/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author JMMOLLER
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        new Login().setImageLabel(Hero, "CamionGas.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound = new Interfaces.PanelRound();
        PanelRegistro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNombreUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfContraseña = new javax.swing.JPasswordField();
        panelRound2 = new Interfaces.PanelRound();
        btnIngresarLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfContraseña2 = new javax.swing.JPasswordField();
        Hero = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1030, 570));

        panelRound.setBackground(new java.awt.Color(35, 35, 35));
        panelRound.setPreferredSize(new java.awt.Dimension(1230, 530));
        panelRound.setRoundBottomLeft(30);
        panelRound.setRoundBottomRight(30);
        panelRound.setRoundTopLeft(30);
        panelRound.setRoundTopRight(30);
        panelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelRegistro.setBackground(new java.awt.Color(27, 27, 27));
        PanelRegistro.setForeground(new java.awt.Color(204, 204, 204));
        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 209, 195));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registrate");
        PanelRegistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 330, 56));

        jLabel5.setForeground(new java.awt.Color(255, 180, 40));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar (2).png"))); // NOI18N
        PanelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, 46));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Usuario:");
        PanelRegistro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        tfNombreUser.setBackground(new java.awt.Color(56, 56, 56));
        tfNombreUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNombreUser.setForeground(new java.awt.Color(204, 204, 204));
        tfNombreUser.setBorder(new EmptyBorder(10, 10, 10, 10));
        PanelRegistro.add(tfNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 236, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Contraseña:");
        PanelRegistro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        tfContraseña.setBackground(new java.awt.Color(56, 56, 56));
        tfContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfContraseña.setForeground(new java.awt.Color(204, 204, 204));
        tfContraseña.setBorder(new EmptyBorder(10,10,10,10));
        tfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseñaActionPerformed(evt);
            }
        });
        PanelRegistro.add(tfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 236, 40));

        panelRound2.setBackground(new java.awt.Color(43, 209, 195));
        panelRound2.setForeground(new java.awt.Color(255, 255, 255));
        panelRound2.setToolTipText("");
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);

        btnIngresarLogin.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresarLogin.setText("Registrar");
        btnIngresarLogin.setContentAreaFilled(false);
        btnIngresarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIngresarLogin.setSelected(true);
        btnIngresarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarLoginMouseClicked(evt);
            }
        });
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnIngresarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelRegistro.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Email:");
        PanelRegistro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        tfContraseña2.setBackground(new java.awt.Color(56, 56, 56));
        tfContraseña2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfContraseña2.setForeground(new java.awt.Color(204, 204, 204));
        tfContraseña2.setBorder(new EmptyBorder(10,10,10,10));
        tfContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContraseña2ActionPerformed(evt);
            }
        });
        PanelRegistro.add(tfContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 236, 40));

        panelRound.add(PanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, 410));

        Hero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CamionGas.png"))); // NOI18N
        Hero.setText("jLabel1");
        Hero.setPreferredSize(new java.awt.Dimension(589, 550));
        panelRound.add(Hero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 570));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosehandleClick(evt);
            }
        });
        panelRound.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 10, 25, 25));

        lblLogin.setForeground(new java.awt.Color(0, 102, 255));
        lblLogin.setText("¿Ya tienes cuenta?");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginhandleRegisterClick(evt);
            }
        });
        panelRound.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClosehandleClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosehandleClick
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnClosehandleClick

    private void tfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseñaActionPerformed

    private void btnIngresarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarLoginMouseClicked

    private void btnIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoginActionPerformed

    }//GEN-LAST:event_btnIngresarLoginActionPerformed

    private void tfContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContraseña2ActionPerformed

    private void lblLoginhandleRegisterClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginhandleRegisterClick
        Login view = new Login();
        this.dispose();
        view.setVisible(true);
    }//GEN-LAST:event_lblLoginhandleRegisterClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hero;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnIngresarLogin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLogin;
    private Interfaces.PanelRound panelRound;
    private Interfaces.PanelRound panelRound2;
    private javax.swing.JPasswordField tfContraseña;
    private javax.swing.JPasswordField tfContraseña2;
    private javax.swing.JTextField tfNombreUser;
    // End of variables declaration//GEN-END:variables
}
